
[[_introduction]]
= Introduction

Allows controller actions to ve invoked as promises. Relies on {link_jdeferred} as promise implementation.

There are two ways to configure an action as a promise: `implicit` and `explicit`

.Implicit Mode

Requires applying the `{link_griffon_promise}` annotation to the action method, making sure it returns a value.
For example:

[source,groovy,options="nowrap"]
.griffon-app/controllers/com/acme/SampleController.groovy
----
package com.acme

import griffon.core.artifact.GriffonController
import griffon.inject.MVCMember
import griffon.metadata.ArtifactProviderFor
import griffon.plugins.jdeferred.Promise
import org.codehaus.griffon.runtime.core.artifact.AbstractGriffonController
import javax.annotation.Nonnull

@ArtifactProviderFor(GriffonController)
class SampleController extends AbstractGriffonController {
    @MVCMember @Nonnull SampleModel model

    @Promise
    int implicitMode() {
        model.count = model.count + 1
        model.count
    }
}
----

The return value of the action will be set as the resolved value of the JDeferred `Promise`. Any exceptions that may occur
during the action's execution will set as the ``Promise``s  rejected value.

.Explicit Mode

This mode gives you further control on when a value may be resolved or rejected; it alos allows you to publish intermediate
results by calling `notify`. For example

[source,groovy,options="nowrap"]
.griffon-app/controllers/com/acme/SampleController.groovy
----
package com.acme

import griffon.core.artifact.GriffonController
import griffon.core.controller.ControllerAction
import griffon.inject.MVCMember
import griffon.metadata.ArtifactProviderFor
import org.codehaus.griffon.runtime.core.artifact.AbstractGriffonController
import org.jdeferred.Deferred
import javax.annotation.Nonnull

@ArtifactProviderFor(GriffonController)
class SampleController extends AbstractGriffonController {
    @MVCMember @Nonnull SampleModel model

    @ControllerAction
    void explicitMode(@Nonnull Deferred deferred) {
        model.count = model.count + 1
        1.upto(3) { deferred.notify(it) }
        deferred.resolve(model.count)
    }
}
----

Any exceptions that may occur during the action's execution will be set as the ``Promise``s  rejected value if the
promise has not been resolved at that point.

== Handling Results

Typically you'll register callbacks on a `Promise` in order to handle results and errors delivered by the promise.
However promises are not available until the action is about to bhe executed, that's too late to register a callback.
For this reason, the jdeferred plugin allows you to record callbacks ahead of time, using {link_recording_promise} in
combination with {link_promise_manager}. Here's how callbacks can be set on a `view` during it's intialization

[source,java,options="nowrap"]
.griffon-app/views/com/acme/SampleView.java
----
package com.acme;

import griffon.core.artifact.GriffonView;
import griffon.inject.MVCMember;
import griffon.metadata.ArtifactProviderFor;
import griffon.plugins.jdeferred.RecordingPromise;
import org.codehaus.griffon.runtime.javafx.artifact.AbstractJavaFXGriffonView;

import javax.annotation.Nonnull;
import javax.inject.Inject;
import java.util.Map;

@ArtifactProviderFor(GriffonView.class)
public class SampleView extends AbstractJavaFXGriffonView {
    @Inject private PromiseManager promiseManager;
    @MVCMember @Nonnull private SampleController controller;

    @Override
    public void mvcGroupInit(@Nonnull Map<String, Object> args) {
        RecordingPromise<String, Throwable, Void> promise = promiseManager.promiseFor(actionFor(controller, "click"));
        promise.done(r -> System.out.println("Result is " + r))
            .fail(Throwable::printStackTrace)
            .always((s, r, j) -> System.out.println("Finished!"));
    }

    @Override
    public void initUI() {
        // build the UI
    }
}
----

Griffon version: {griffon-version}

